GET http://127.0.0.1:8000/api/user

### guardar user
POST http://127.0.0.1:8000/api/user
Content-Type: application/json

{
    "name": "abraham",
    "email": "abraham@gmail.com",
    "password": "123456"
}

### guardar user 2
POST http://127.0.0.1:8000/api/user
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "admin123"
}

### modificar user
PUT http://127.0.0.1:8000/api/user/1
Content-Type: application/json

{
    "name": "abraham modificado",
    "email": "abraham.modificado@gmail.com",
    "password": "admin123"
}

### buscar por id
GET http://127.0.0.1:8000/api/user/1

### eliminar user 1
DELETE  http://127.0.0.1:8000/api/user/1